---
title: "P8105 Homework 4"
date: "2023-10-30"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Distribution of days since prior order

```{r}
# The dataset uses 30 to denote >30, so I remove 30 to make the plot easier to read
instacart_lt30 <- instacart |> 
  filter(days_since_prior_order < 30)
  
instacart_lt30 |> 
  plot_ly(x = ~days_since_prior_order, type = "histogram", 
          name = "Days Since Prior Order")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Hour of Day by Aisle

```{r}
instacart |> 
  filter(aisle %in% c("fresh fruits", "fresh vegetables", "yogurt", "ice cream ice")) |> 
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "violin")
```

### Reorder vs. First-time Order by Aisle

```{r}
instacart |> 
  filter(aisle %in% c("fresh fruits", "fresh vegetables", "yogurt", "ice cream ice")) |> 
  group_by(aisle, reordered) |> 
  count() |> 
  mutate(reordered = case_match(reordered, 0 ~ "No", 1 ~ "Yes")) |> 
  pivot_wider(id_cols = aisle, names_from = reordered, values_from = n) |> 
  plot_ly(x = ~aisle, y = ~Yes, type = "bar", name = "Reorder") |> 
  add_trace(y = ~No, name = "First-time Order") |> 
  layout(yaxis = list(title = 'Count'), barmode = 'stack')
```

